### Send access code user
POST http://localhost:5000/api/auth/request-code
Content-Type: application/json

{
  "email": "njuirik15@gmail.com"
}

### Verify access code user

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "njuirik15@gmail.com",
  "password": "testpassword",
  "accessCode": "263574" 
}

### Login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "testpassword"
}
